config/routes.rb
Darksouls::Application.routes.draw do
  resources :profiles

  root :to => 'pages#index'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new params[:profile]
    if @profile.save
      redirect_to :action => :index
    else
      render :new
    end
  end

  def index
    @profiles = Profile.all
  end
  
  def show
    @profile = Profile.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dark Souls Character Builder</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
  <script src="/js/jquery.base64.js"></script>
  <script src="/js/main.js"></script>
  <link rel="stylesheet" href="/css/default.css" type="text/css" media="screen" title="default" charset="utf-8">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>

  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
  <%= csrf_meta_tags %>

  <%- if Rails.env.production? -%>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-6677889-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
  <%- end -%>

</head>
<body>

  <div id="wrapFullPage">
    <div id="content">
      <div id="header">
        <img src="/images/logo.png" />
        <h2>Update Coming Soon</h2>
      </div>
      <div id="twitter">
        <div class="the960"><p><a href="http://twitter.com/itg" class="twitterLogo">Add Me</a></p></div>
      </div>

      <%= yield %>

    </div>
  </div>


</body>
</html>

app/views/pages/index.html.erb
<div id="wrapBuilder">
  <div id="colLeft" class="the300">
    <div id="wrapClass">
      <label>Class</label>
      <select id="class" onchange="" size="1">
        <option value="Warrior">4 - Warrior</option>
        <option value="Knight">5 - Knight</option>
        <option value="Wanderer">3 - Wanderer</option>
        <option value="Thief">5 - Thief</option>
        <option value="Bandit">4 - Bandit</option>
        <option value="Hunter">4 - Hunter</option>
        <option value="Sorcerer">3 - Sorcerer</option>
        <option value="Pyromancer">1 - Pyromancer</option>
        <option value="Cleric">2 - Cleric</option>
        <option value="Deprived">6 - Deprived</option>

      </select>
    </div>
    <p />
    <div class="stattitles">
      <label></label>
      <div class="title" >STARTING</div>
      <div class="title">CURRENT</div>
    </div>
    <div id="soullevel" class="stat">
      <label>Soul Level</label>
      <div class="start" ></div>
      <input class="current" readonly />
    </div>

    <hr />

    <div class="stattitles">
      <label></label>
      <div class="title" >STARTING</div>
      <div class="title">CURRENT</div>
    </div>

    <div id="vitality" class="stat">
      <div class="statShift">
        <input type="submit" class="subtract" value="" />
        <input type="submit" class="add" value="" />
      </div>
      <label>Vitality</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="1" />
    </div>

    <div id="attunement" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>
      <label>Attunement</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="2" />

    </div>

    <div id="endurance" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>
      <label>Endurance</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="3" />

    </div>

    <div id="strength" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>  
      <label>Strength</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="4" />
    </div>

    <div id="dexterity" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>
      <label>Dexterity</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="5" />
    </div>

    <div id="resistance" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>    
      <label>Resistance</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="6" />
    </div>

    <div id="intelligence" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>    
      <label>Intelligence</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="7" />
    </div>

    <div id="faith" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>
      <label>Faith</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="8" />
    </div>

    <hr />

    <div id="calc">   
      <div class="title right">TOTAL SOUL COST</div><div class="title" >CURRENT SOUL COST</div>
      <div class="total right"></div><input class="current" readonly />
    </div>

  </div>

<!-- MIDDLE -->
  <div id="colMid" class="the300">
    <div id="HP" class="stat">
      <label>HP</label><input class="current right" readonly />
    </div>

    <div id="stamina" class="stat">
      <label>Stamina</label><input class="current right" readonly />
    </div>

    <div id="equipload" class="stat">
      <label>Equip Load</label><input class="current right" readonly />
    </div>
  </div>


  <div id="colRight" class="the300">
    <div id="poise" class="stat">
      <label>Poise</label><input class="current right" readonly />
    </div>

    <div id="bleedresist" class="stat">
      <label>Bleed Resist</label><input class="current right" readonly />
    </div>

    <div id="poisonresist" class="stat">
      <label>Poison Resist</label><input class="current right" readonly />
    </div>

    <div id="curseresist" class="stat">
      <label>Curse Resist</label><input class="current right" readonly />
    </div>
    
    <div id="spellslots" class="stat">
      <label>Spell Slots</label><input class="current right" readonly />
    </div>
  </div>
  
  <div id="wrapCode">
    Copy this URL to your clipboard to share this build:<br/>
    <input id="templateCode" />
  </div>
</div>

<div id="footer">
  <%- if Rails.env.production? -%>
  <div style="clear:both"><br/><hr /><br/></div>

  <div id="disqus_thread"></div>
    <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'soulbuilder'; // required: replace example with your forum shortname
      var disqus_identifier = '2583573';

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function()
      {
        var dsq = document.createElement('script');
        dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
      console.debug(document.getElementsByTagName('head')[0]);
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <%- end -%>
</div>

<%- if Rails.env.production? -%>
<script type="text/javascript">
  var host = ('https:' == document.location.protocol ? 'https://ssl.' : 'http://met.');
  document.write(unescape("%3Cscript src='" + host + "picnet.com.au/resources/scripts/met.client.min.js?usercode=227152192924864' type='text/javascript'%3E%3C/script%3E"));
</script>
<script src="//static.getclicky.com/js" type="text/javascript"></script>
<script type="text/javascript">try{ clicky.init(66489646); }catch(e){}</script>
<noscript></noscript>
<%- end -%>
<script type="text/javascript">
  $(document).ready(function()
  {
    // Run the CharSetup function
    var params = GetCode($.getUrlVar("c"));	
    CharSetup(params);
  });
</script>

app/views/profiles/_stat_builder.html.erb
<div id="wrapBuilder">
  <div id="colLeft" class="the300">
    <div id="wrapClass">
      <label>Class</label>
      <select id="class" onchange="" size="1">
        <option value="Warrior">4 - Warrior</option>
        <option value="Knight">5 - Knight</option>
        <option value="Wanderer">3 - Wanderer</option>
        <option value="Thief">5 - Thief</option>
        <option value="Bandit">4 - Bandit</option>
        <option value="Hunter">4 - Hunter</option>
        <option value="Sorcerer">3 - Sorcerer</option>
        <option value="Pyromancer">1 - Pyromancer</option>
        <option value="Cleric">2 - Cleric</option>
        <option value="Deprived">6 - Deprived</option>

      </select>
    </div>
    <p />
    <div class="stattitles">
      <label></label>
      <div class="title" >STARTING</div>
      <div class="title">CURRENT</div>
    </div>
    <div id="soullevel" class="stat">
      <label>Soul Level</label>
      <div class="start" ></div>
      <input class="current" readonly />
    </div>

    <hr />

    <div class="stattitles">
      <label></label>
      <div class="title" >STARTING</div>
      <div class="title">CURRENT</div>
    </div>

    <div id="vitality" class="stat">
      <div class="statShift">
        <input type="submit" class="subtract" value="" />
        <input type="submit" class="add" value="" />
      </div>
      <label>Vitality</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="1" />
    </div>

    <div id="attunement" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>
      <label>Attunement</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="2" />

    </div>

    <div id="endurance" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>
      <label>Endurance</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="3" />

    </div>

    <div id="strength" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>  
      <label>Strength</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="4" />
    </div>

    <div id="dexterity" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>
      <label>Dexterity</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="5" />
    </div>

    <div id="resistance" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>    
      <label>Resistance</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="6" />
    </div>

    <div id="intelligence" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>    
      <label>Intelligence</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="7" />
    </div>

    <div id="faith" class="stat">
      <div class="statShift">
        <input type="button" class="subtract" value="" />
        <input type="button" class="add" value="" />
      </div>
      <label>Faith</label>
      <div class="start" ></div>
      <input class="current edit" tabindex="8" />
    </div>

    <hr />

    <div id="calc">   
      <div class="title right">TOTAL SOUL COST</div><div class="title" >CURRENT SOUL COST</div>
      <div class="total right"></div><input class="current" readonly />
    </div>

  </div>

<!-- MIDDLE -->
  <div id="colMid" class="the300">
    <div id="HP" class="stat">
      <label>HP</label><input class="current right" readonly />
    </div>

    <div id="stamina" class="stat">
      <label>Stamina</label><input class="current right" readonly />
    </div>

    <div id="equipload" class="stat">
      <label>Equip Load</label><input class="current right" readonly />
    </div>
    
  </div>


  <div id="colRight" class="the300">
    <div id="poise" class="stat">
      <label>Poise</label><input class="current right" readonly />
    </div>

    <div id="bleedresist" class="stat">
      <label>Bleed Resist</label><input class="current right" readonly />
    </div>

    <div id="poisonresist" class="stat">
      <label>Poison Resist</label><input class="current right" readonly />
    </div>

    <div id="curseresist" class="stat">
      <label>Curse Resist</label><input class="current right" readonly />
    </div>
    
    <div id="spellslots" class="stat">
      <label>Spell Slots</label><input class="current right" readonly />
    </div>
  </div>
  
  <div id="wrapCode">
    Copy this URL to your clipboard to share this build:<br/>
    <input id="templateCode" />
  </div>
</div>

app/views/profiles/index.html.haml
%h1 Profile list (using HAML)

%ul
  - @profiles.each do |profile|
    %li= link_to profile.name, profile

= link_to "Create a new Profile", new_profile_path

app/views/profiles/new.html.haml
!= render :partial => 'stat_builder'

= form_for @profile do |f|
  - if f.object.errors.any?
    %ul
      - f.object.errors.full_messages.each do |msg|
        %li= msg
  = f.label :name
  = f.text_field :name
  = f.submit
  = f.hidden_field :stats

:javascript
  $(document).ready(function()
  {
    // Run the CharSetup function
    var params = GetCode($("#profile_stats").val());
    CharSetup(params);
  });

app/views/profiles/show.html.haml
!= render :partial => 'stat_builder'

:javascript
  $(document).ready(function()
  {
    // Run the CharSetup function
    var params = GetCode("#{@profile.stats}");
    CharSetup(params);
  });